language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
script:
  - npm run lint
  - npm run test
  - npm run build
branches:
  only:
    - master
after_success:
  - npm run cover
  - npm run report-coverage
